create table if not exists public.death_counts_by_quarter_and_county_2020
(
    id integer not null,
    data_as_of character varying(50) collate pg_catalog."default",
    start_date character varying(50) collate pg_catalog."default",
    end_date character varying(50) collate pg_catalog."default",
    year integer,
    quarter integer,
    state character varying(50) collate pg_catalog."default",
    county character varying(50) collate pg_catalog."default",
    fips_state integer,
    fips_county integer,
    fips_code integer,
    urban_rural_code character varying(50) collate pg_catalog."default",
    age_group character varying(50) collate pg_catalog."default",
    covid_19_deaths integer,
    total_deaths integer,
    footnote character varying(255) collate pg_catalog."default",
    constraint death_counts_by_quarter_and_county_2020_pkey primary key (id)
);

create table if not exists public.deaths_by_cause_2019_2021
(
    id integer,
    date_of_death_year integer,
    date_of_death_month integer,
    hhs_region text collate pg_catalog."default",
    age_group text collate pg_catalog."default",
    all_cause integer,
    natural_cause integer,
    septicemia integer,
    malignant_neoplasms integer,
    diabetes_mellitus integer,
    alzheimer_disease integer,
    influenza_and_pneumonia integer,
    chronic_lower_respiratory_diseases integer,
    other_diseases_of_respiratory_system integer,
    nephritis_nephrotic_syndrome_and_nephrosis integer,
    symptoms_signs_and_abnormal_clinical_and_laboratory_findings_no integer,
    diseases_of_heart integer,
    cerebrovascular_diseases integer,
    covid_19 integer,
    covid_19_1 integer,
    note text collate pg_catalog."default",
    flag_allcause text collate pg_catalog."default",
    flag_natcause text collate pg_catalog."default",
    flag_sept text collate pg_catalog."default",
    flag_neopl text collate pg_catalog."default",
    flag_diab text collate pg_catalog."default",
    flag_alz text collate pg_catalog."default",
    flag_inflpn text collate pg_catalog."default",
    flag_clrd text collate pg_catalog."default",
    flag_otherresp text collate pg_catalog."default",
    flag_nephr text collate pg_catalog."default",
    flag_otherunk text collate pg_catalog."default",
    flag_hd text collate pg_catalog."default",
    flag_stroke text collate pg_catalog."default",
    flag_cov_19_mcod text collate pg_catalog."default",
    flag_cov_19_ucod text collate pg_catalog."default"
);